apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meteo
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
          - path: /meteo
            pathType: ImplementationSpecific
            backend:
              service:
                name: meteo-service-svc
                port:
                  number: 8083
          - path: /feedbacks
            pathType: ImplementationSpecific
            backend:
              service:
                name: meteo-service-svc
                port:
                  number: 8082
          - path: /places
            pathType: ImplementationSpecific
            backend:
              service:
                name: meteo-service-svc
                port:
                  number: 8084



