apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server-config
data:
  SPRING_PROFILES_ACTIVE: "native,prod"
  EUREKA_SERVICE_ADDRESS: "http://eureka-0.eureka.default.svc.cluster.local:8761/eureka"
