apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedbacks-service-app
  labels:
    app: feedbacks-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedbacks-service-app
  template:
    metadata:
      labels:
        app: feedbacks-service-app
    spec:
      containers:
        - name: feedbacks-service-app
          image: matteosevergninistudent/feedbacks
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: POSTGRES_HOST   # Setting Database host address
              value: postgresql-service
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: password
