kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
      - name: frontend-service
        image: nurbani50/frontend-service
        ports:
        - containerPort: 80
