apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend-service
spec:
  selector:
    app: frontend-service
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80

