name: Build and Deploy Microservices

on:
  push:
    branches: [ main ]
    paths:
      - '**/*'
      - '!frontend-service/**/*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: config-server
          - service: server-registry
          - service: api-gateway
          - service: feedbacks
          - service: meteo
          - service: places
          - service: frontend-service
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean install -DskipTests -f ./${{ matrix.service }}/pom.xml
    
    - name: Build Docker image
      run: docker build -t matteosevergninistudent/${{ matrix.service }}:latest ./${{ matrix.service }}
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push Docker image to Docker Hub
      run: docker push matteosevergninistudent/${{ matrix.service }}:latest
